function [y, u, theta, ptheta] = tapas_mpdcm_erp_standard_data_set()
%% Generate a standard data set to be used for testing. 
%
% Input
%
% Output
%
%

% aponteeduardo@gmail.com
% copyright (C) 2016
%

u = linspace(0, 10, 1000);
u = 30 * normpdf(5 * (u + 0.3));
y = ones(1, 5000);

theta = struct(...
    'dim_x', 1, ...
    'dim_u', 1, ...
    'Au', 0.1, ...
    'gamma1', 0.1, ...
    'gamma2', 0.1, ...
    'gamma3', 0.1, ...
    'gamma4', 0.1, ...
    'r1', 0.1, ...
    'r2', 0.1, ...
    'er1r2', 0.1, ...
    'tau_e2', 0.1, ...
    'tau_es2', 0.1, ...
    'tau_i2', 0.1, ...
    'tau_is2', 0.1, ...
    'A13', [0.2], ...
    'A23', [0.2]);
ptheta = struct(...
    'udt', 0.00025, ...
    'dyu', 1.0, ...
    'dt', 1);

y = {y};
u = {u};
theta = {theta};
ptheta = ptheta;

end % tapas_mpdcm_erp_standard_data_set 

