function test_tapas_mpdcm_erp(fp)
%% Test 
%
% fp -- Pointer to a file for the test output, defaults to 1
%
% aponteeduardo@gmail.com
% copyright (C) 2016
%

if nargin < 1
    fp = 1;
end

fname = mfilename();
fname = regexprep(fname, 'test_', '');


fprintf(fp, '================\n Test %s\n================\n', fname);


theta = struct('dim_x', 1, 'dim_u', 1, 'columns', []);

column = struct(...
    'dim_x', 1, ...
    'dim_u', 1, ...
    'Au', 0.1, ...
    'gamma1', 0.1, ...
    'gamma2', 0.1, ...
    'gamma3', 0.1, ...
    'gamma4', 0.1, ...
    'r1', 0.1, ...
    'r2', 0.1, ...
    'er1r2', 0.1, ...
    'tau_e2', 0.1, ...
    'tau_es2', 0.1, ...
    'tau_i2', 0.1, ...
    'tau_is2', 0.1, ...
    'A13', [0.1], ....
    'A23', [0.1], ...);

theta.columns = {column};

ptheta = struct(...
    'dy', 0.1, ...
    'du', 0.1, ...
    'dyu', 0.1, ...
    'de', 0.1, ...
    'dt', 0.1);

u = ones(4, 5000)';


% Test whether there is any clear bug
try
    fprintf(fp, '       Passed\n');
catch err
    fprintf(fp, '   Not passed at line %d\n', err.stack(end).line);
    fprintf(fp, getReport(err, 'extended'));
end


end

